### ISSUE TITLE
[vault backend] /data is appended when using v1 KV secret engine

### ISSUE THREAD

**Issue by c35sys** [itscontained/secret-manager#41]
When using the following SecretStore manifest, I've got a 404 in the logs because **/data** is appended.
```
apiVersion: secret-manager.itscontained.io/v1alpha1
kind: SecretStore
metadata:
  name: vault
  namespace: example-ns
spec:
  vault:
    server: "https://xxx:8200"
    path: testkv
    version: v1
...
```
