### ISSUE TITLE
Add v1alpha2 ExternalSecret

### ISSUE THREAD

**Issue by mcavoyk** [itscontained/secret-manager#48]
Based on changes discussed in https://github.com/godaddy/kubernetes-external-secrets/pull/47. Changes to data block and template.

Example of larger breaking changes:
```yaml
apiVersion: secret-manager.itscontained.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example
spec:
  data:
  - remoteRef:
      name: path/or-id
      property: value
    secretKey: example
  storeRef:
    name: vault
  template:
    metadata:
      annotations:
        new-annotation: example
```

becomes

```yaml
apiVersion: secret-manager.itscontained.io/v1alpha2
kind: ExternalSecret
metadata:
  name: example
spec:
  data:
    example:
      key: path/or-id
      property: value
  storeRef:
    name: vault
  target: 
    template:
      metadata:
        annotations:
          new-annotation: example
```
