### ISSUE TITLE
support to create aws-ssm full secret string as key in k8s secret

### ISSUE THREAD

**Issue by kernel164** [itscontained/secret-manager#88]
**Is your feature request related to a problem? Please describe.**
I would like to create k8s secret with key "config.json" and value as SecretString retrieved from AWS SSM.

**Describe the solution you'd like**

```yaml
apiVersion: secret-manager.itscontained.io/v1alpha1
kind: ExternalSecret
metadata:
  name: app-config
  namespace: app
spec:
  storeRef:
    name: aws-ssm
  data:
  - secretKey: config.json
     remoteRef:
       name: app-config
       property: "" // empty string denotes full secret string
```

**Describe alternatives you've considered**
There is no way to do it right now.
