### ISSUE TITLE
charts.itscontained.io is down - or was it permanently removed?

### ISSUE THREAD

**Issue by huguesalary** [itscontained/secret-manager#89]
I use charts.itscontained.io to install your helm chart, but today I'm getting an error message telling me 

```
Error: looks like "https://charts.itscontained.io" is not a valid chart repository or cannot be reached: Get https://charts.itscontained.io/index.yaml: dial tcp 167.99.26.57:443: connect: connection timed out
```

Are you temporarily down or did you permanently take charts.itscontained.io down?

**Comment by dirtycajunrice** [comment]
looks like that was my bad! I upgraded the cluster doing the proxying and it didnt pick up the change. It should be working again. Thanks for the heads up!
```
curl -s https://charts.itscontained.io/index.yaml | head -n 5
apiVersion: v1
entries:
  bitwarden_rs:
  - apiVersion: v2
    appVersion: 1.16.3
```
